import type { Metadata } from "next";
import "./global.css";
import { roboto } from "@/lib/fonts";
import NavigationMenu from "@/components/NavigationMenu/NavigationMenu";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { AuthProvider } from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex bg-gradient-to-br from-gray-900 via-purple-900 to-violet-900">
        <ReactQueryProvider>
           <AuthProvider>
          <NavigationMenu />
          {children}
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
